## REMEMBER TO SET UP YOUR GITHUB REPO FOR TRAVIS
## Go to: https://travis-ci.org/monarch-initiative for details
sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull

# command to run tests
script: cd src/ontology && sh run.sh make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master
    - test-travis

### Add your own lists here
### See https://github.com/INCATools/ontology-development-kit/issues/35
notifications:
  email:
    recipients:
      - Leigh.Carmody@jax.org
      - nicolas.matentzoglu@gmail.com
      - peter.robinson@jax.org
      - vasilevs@ohsu.edu
      - chanl@oregonstate.edu
    on_success: change
    on_failure: always
